# Generated by Django 5.2.7 on 2025-11-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Ingrese el número de mesa', unique=True)),
                ('capacity', models.IntegerField(help_text='Ingrese la capacidad de la mesa')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved')], default='AVAILABLE', help_text='Estado de la mesa', max_length=10)),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la orden')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PREPARING', 'En Preparación'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Estado de la orden', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la orden', max_digits=10)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Para comer aquí'), ('TAKEOUT', 'Para llevar'), ('DELIVERY', 'Delivery')], default='DINE_IN', help_text='Tipo de orden', max_length=10)),
                ('delivery', models.ForeignKey(blank=True, help_text='Información de delivery (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.delivery')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'órdenes',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Cantidad del plato')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal', max_digits=10)),
                ('dish', models.ForeignKey(help_text='Plato ordenado', on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('order', models.ForeignKey(help_text='Orden asociada', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'detalle de orden',
                'verbose_name_plural': 'detalles de órdenes',
                'unique_together': {('order', 'dish')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(help_text='Platos de la orden', through='orders.OrderDetail', to='dishes.dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Seleccione la mesa (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.table'),
        ),
    ]
