# Generated by Django 5.2.7 on 2025-11-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del repartidor', max_length=100)),
                ('phone', models.CharField(help_text='Ingrese el teléfono del repartidor', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='AVAILABLE', help_text='Estado del repartidor', max_length=10)),
            ],
            options={
                'verbose_name': 'repartidor',
                'verbose_name_plural': 'repartidores',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Ingrese la dirección de entrega', max_length=255)),
                ('phone', models.CharField(help_text='Ingrese el teléfono de contacto', max_length=20)),
                ('customer_name', models.CharField(help_text='Ingrese el nombre del cliente', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Ingrese el costo del delivery', max_digits=10)),
                ('delivery_person', models.ForeignKey(blank=True, help_text='Seleccione el repartidor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.deliveryperson')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
            },
        ),
    ]
