# Generated by Django 5.2.7 on 2025-11-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del plato', max_length=100)),
                ('description', models.TextField(help_text='Ingrese la descripción del plato')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ingrese el precio del plato', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Estado del plato', max_length=8)),
                ('category', models.ForeignKey(help_text='Seleccione la categoría del plato', on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'plato',
                'verbose_name_plural': 'platos',
            },
        ),
    ]
